---
- name: Install php
  apt:
    name: "{{ php_packages }}"
    install_recommends: no
    state: present

- name: Get php installed packages
  package_facts:
    manager: apt

- name: Get php version
  debug:
    var: "{{ ansible_facts.packages['php']['version'] }}"

- name: Set php version
  set_fact:
    php_version: "{{ ansible_facts.packages['php']['version'] }}"

- name: Enable service
  systemd:
    name: php{{ php_version }}-fpm
    enabled: yes

- name: Change default php.ini
  lineinfile:
    path: /etc/php/{{ php_version }}/fpm/php.ini
    state: present
    regexp: ';cgi.fix_pathinfo=1'
    line: 'cgi.fix_pathinfo=0'
    backup: yes
