---
- name: Converge
  hosts: all
  vars:
    https: "{{ lookup('env', 'HTTPS') }}"
    cloudflare: "{{ lookup('env', 'CLOUDFLARE') }}"
    staging: "{{ lookup('env', 'STAGING') }}"
  roles:
    - role: aminvakil.httpd_initial
