---
- name: Converge
  hosts: all
  vars:
    https: "{{ lookup('env', 'HTTPS') }}"
    cloudflare: "{{ lookup('env', 'CLOUDFLARE') }}"
    staging: "{{ lookup('env', 'STAGING') }}"
    mysql_initial: "{{ lookup('env', 'MYSQL_INITIAL') }}"
  roles:
    - role: create_user
    - role: httpd_initial
    - role: nginx_initial
    - role: mysql_initial
    - role: mysql_add_user
    - role: php_initial
