---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "quay.io/aminvakil/${MOLECULE_DISTRO}-systemd:latest"
    tmpfs:
      - /run
      - /tmp
    privileged: true
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      vault_password_file: "${MOLECULE_PROJECT_DIRECTORY}/vault.pw"
