---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "quay.io/aminvakil/${MOLECULE_DISTRO}-systemd:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  config_options:
    defaults:
      vault_password_file: "${MOLECULE_PROJECT_DIRECTORY}/vault.pw"
