---
- name: Create group {{ user_name }}
  group:
    name: "{{ user_name }}"
    system: true
    state: present

- name: Create user {{ user_name }}
  user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    system: true
    create_home: true
    home: /srv/{{ user_name }}
    shell: /sbin/nologin

- name: Change permissions of /srv/{{ user_name }}
  file:
    path: /srv/{{ user_name }}
    mode: '0711'

- name: Create public_html in /srv/{{ user_name }}
  file:
    path: "{{ item }}"
    state: directory
    mode: '0711'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  loop:
    - /srv/{{ user_name }}/public_html
    - /srv/{{ user_name }}/tmp
    - /srv/{{ user_name }}/tmp/session
    - /srv/{{ user_name }}/tmp/upload
